
@baseUrl = https://localhost:7979

### PM 1

POST {{baseUrl}}/token/generate
content-type: application/json

{
  "Id": "11111111-1111-1111-1111-111111111111",
  "FirstName": "Issam",
  "LastName": "A.",
  "Email": "issam.a@localhost",
  "Permissions": [
    "project:create",
    "project:read",
    "project:update",
    "project:delete",
    "project:manage_budget",
    "task:create",
    "task:read",
    "task:update",
    "task:delete",
    "task:assign_user",
    "task:update_status"
  ],
  "Roles": [
    "ProjectManager"
  ]
}

### Team #1
POST {{baseUrl}}/api/token/generate
content-type: application/json

{
        
  "Id": "55555555-5555-5555-5555-555555555555",
  "FirstName": "Sarah",
  "LastName": "Lee",
  "Email": "sarah.lee@localhost",
  "Permissions": [
    "project:read",
    "task:read",
    "task:update_status"
  ],
  "Roles": [
    "TeamMember"
  ]
}

### Team #2
POST {{baseUrl}}/api/token/generate
content-type: application/json

{
        
  "Id": "22222222-2222-2222-2222-222222222222",
  "FirstName": "John",
  "LastName": "Doe",
  "Email": "john.doe@localhost",
  "Permissions": [
    "project:read",
    "task:read",
    "task:update_status"
  ],
  "Roles": [
    "TeamMember"
  ]
}

###

POST {{baseUrl}}/api/token/generate
content-type: application/json

{ 
  "Id": "33333333-3333-3333-3333-333333333333",
  "FirstName": "Emily",
  "LastName": "White",
  "Email": "emily.white@localhost",
  "Permissions": [
    "project:read",
    "task:read"
  ],
  "Roles": [
    "Stakeholder"
  ]
}


###
POST {{baseUrl}}/api/token/refresh-token
Content-Type: application/json

{
  "refreshToken": "7a6f23b4e1d04c9a8f5b6d7c8a9e01f1"
}